name: 'Lowell Downey Photography & Written word'
favicon: null
layout_spectrum: 0.9461928277742118
typography_spectrum: 0.7834273118060082
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00020b'
    - '#ffffff'
    - '#08404b'
    - '#c5bf89'
    - '#2c5bd5'
  brandStrength: 0.375
  lightness: 0.9489679425023496
  saturation: 0.8097938701976091
  rhythmicContrast: 0.6654356878716499
purpose: []
