name: 'The Art of Seeing and Being- Lowell Downey Photography & Written word'
favicon: null
layout_spectrum: 0.62897
typography_spectrum: 0.92693
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#aeb9c9'
    - '#8ba4c6'
    - '#4d7e14'
    - '#205203'
    - '#7bac40'
  brandStrength: 0.5625
  lightness: 0.625
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
